# Generated by Django 4.1.7 on 2023-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titles',
            field=models.CharField(db_column='Titles', max_length=200, null=True),
        ),
    ]
