# Generated by Django 4.1.7 on 2023-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_titles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog entries'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Scrubber')], max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titles',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
