# Generated by Django 4.1.7 on 2023-03-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blog_options_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Scrubber'), ('B', 'Brush'), ('BM', 'Bath Bomb'), ('BP', 'Bath Pillow')], max_length=3, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
