# Generated by Django 4.1.7 on 2023-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(blank=True, help_text='Ente your titles name', max_length=200, null=True, verbose_name='Titles')),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(blank=True, help_text='Enter your title name', max_length=200, null=True, verbose_name='Titles')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
            ],
        ),
    ]
