# Generated by Django 4.1.7 on 2023-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='category'),
        ),
    ]
