# Generated by Django 4.1.7 on 2023-03-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0004_post_image_post_post_status_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(blank=True, help_text='Ente your titles name', max_length=200, null=True, verbose_name='Titles')),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
    ]
