# Generated by Django 4.1.7 on 2023-03-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Tag',
            field=models.ManyToManyField(blank=True, null=True, to='dapp.tag'),
        ),
    ]
